[build]
  command = "bun run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  BUN_VERSION = "1.1.38"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@node-rs/argon2", "postgres"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "bun run dev:vite"
  targetPort = 5173
  port = 8888
  autoLaunch = false
